# Pipeline for Databricks workspace import

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - workspace/*

stages:
- stage: "dev"
  displayName: "Development"
  dependsOn: []
  pool:
    vmImage: "ubuntu-latest"
  variables:
    - group: databricks_cli

  jobs:
    - job: SyncWorkspace2Dev
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: "3.8"
            architecture: "x64"

        - script: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt || true
          displayName: "Install Python dependencies"

        - script: |
            pytest tests/ --cov=workspace  --cov-report xml:coverage.xml
          displayName: "Run Pytest Unit Tests"

        - task: ShellScript@2
          inputs:
            scriptPath: pipelines/databricks-cli-config.sh
            args: "$(databricks_host) $(databricks_token)"
          displayName: "Install and configure the Databricks CLI"

        - script: |
            databricks fs cp --recursive --overwrite ../files/ dbfs:/FileStore/
          displayName: "Upload Files"

        - task: ShellScript@2
          inputs:
            scriptPath: pipelines/databricks-workspace-import.sh
            args: "EcommerceWorkspace"
          displayName: "Import updated notebooks to workspace to dev"
